/*
 * generated by Xtext
 */
package eu.ddmore.pml;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PharmMLRuntimeModule extends eu.ddmore.pml.AbstractPharmMLRuntimeModule {

}
