#!/usr/bin/env python

print '''==============================================================
qname        all.q               
hostname     navtst-nonmem.mango.local
group        DomainUsers         
owner        mockuser           
project      NONE                
department   defaultdepartment   
jobname      echo.sh             
jobnumber    9999                
taskid       undefined
account      sge                 
priority     0                   
qsub_time    Wed Jun 27 17:45:30 2012
start_time   Wed Jun 27 17:45:42 2012
end_time     Wed Jun 27 17:45:55 2012
granted_pe   NONE                
slots        1                   
failed       0    
exit_status  1                   
ru_wallclock 13           
ru_utime     0.003        
ru_stime     0.012        
ru_maxrss    1060                
ru_ixrss     0                   
ru_ismrss    0                   
ru_idrss     0                   
ru_isrss     0                   
ru_minflt    836                 
ru_majflt    0                   
ru_nswap     0                   
ru_inblock   0                   
ru_oublock   0                   
ru_msgsnd    0                   
ru_msgrcv    0                   
ru_nsignals  0                   
ru_nvcsw     16                  
ru_nivcsw    3                   
cpu          0.015        
mem          0.000             
io           0.000             
iow          0.000             
maxvmem      0.000
arid         undefined'''
