#!/usr/bin/python

import time

sleeptimesec = 10

print "Sleeping for %s seconds" % sleeptimesec
time.sleep(sleeptimesec)
print "Done"

print '''==============================================================
job_number:                 9999
exec_file:                  job_scripts/9525
submission_time:            Wed Jun 27 17:45:30 2012
owner:                      mockuser
uid:                        10005
group:                      DomainUsers
gid:                        10000
sge_o_home:                 /home/mockuser
sge_o_log_name:             mockuser
sge_o_path:                 /usr/global/sge/bin/lx24-amd64:/home/mockuser/bin:/usr/global/sge/bin/lx24-x86:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/java/bin:/opt/maven/bin:/opt/ant/bin:/opt/ivy:/opt/visualvm/bin:/home/mockuser/spark:/home/mockuser/workspace/navigatorproduct/Source/navigator.dev.properties:/usr/global/sge/bin/lx24-x86:/usr/bin:/opt/scala/bin:/opt/gradle/bin:/opt/ratpack/build/ratpack/bin:/opt/groovy/bin:/opt/jruby/bin
sge_o_shell:                /bin/bash
sge_o_workdir:              /usr/global/mockuser/testsubmit
sge_o_host:                 mango-laptop29
account:                    sge
cwd:                        /usr/global/mockuser/testsubmit
mail_list:                  mockuser@mango-laptop29.Mango.local
notify:                     FALSE
job_name:                   echo.sh
jobshare:                   0
env_list:                   
script_file:                echo.sh
scheduling info:            (Collecting of scheduler job information is turned off)'''
