/*
 * generated by Xtext
 */
package eu.ddmore.mdl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import eu.ddmore.mdl.MdlRuntimeModule;
import eu.ddmore.mdl.MdlStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MdlIdeSetup extends MdlStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MdlRuntimeModule(), new MdlIdeModule()));
	}
	
}
