/*
* generated by Xtext
*/
package eu.ddmore.pml.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class PharmMLOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
