/*
 * generated by Xtext
 */
package eu.ddmore.pml.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import eu.ddmore.pml.ui.internal.PharmMLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PharmMLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PharmMLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PharmMLActivator.getInstance().getInjector(PharmMLActivator.EU_DDMORE_PML_PHARMML);
	}
	
}
