/*
 * generated by Xtext
 */
package org.ddmore.pml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PharmaMLUiModule extends org.ddmore.pml.ui.AbstractPharmaMLUiModule {
	public PharmaMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
