/*
 * generated by Xtext
 */
package eu.ddmore.mdl.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class MdlWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public MdlWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
