package com.mango.mif.core;


import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;
import static org.hamcrest.CoreMatchers.nullValue;
import static org.junit.Assert.assertThat;

import java.util.UUID;

import javax.annotation.Resource;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import com.mango.mif.connector.dispatcher.dao.JobDao;
import com.mango.mif.connector.dispatcher.domain.Job;
import com.mango.mif.connector.dispatcher.domain.MIFException;
import com.mango.mif.utils.ExecutionUtilsTest;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = {
		"/spring/test-hibernate-context.xml",
		"/spring/test-Springcontext.xml"
	 })
public class JobPersistenceTest {
	
	@Resource(name = "jobDao")
	private JobDao executionRequestDao;

	@Test
	public void saveAndRetrieveProfileAndWorkFlowInfo() throws MIFException {
		UUID randomUUID = UUID.randomUUID();
		Job job = new Job();
		String clientReqMessage = ExecutionUtilsTest.buildMessage(randomUUID);
		job.setExecutionRequestMsg(clientReqMessage);
		job.setJobId(randomUUID.toString());
		assertThat("Must not contain an ID", job.getId(), is(nullValue()));
		Job savedJob = executionRequestDao.save(job);
		
		assertThat("Id must be generated By Hiberante", savedJob.getId(), is(notNullValue()));
		assertThat("Job ID", savedJob.getJobId(), is(equalTo(randomUUID.toString())));
		assertThat("Message Must be equal ", savedJob.getExecutionRequestMsg(), is(equalTo(clientReqMessage)));
	}

}
