/*
* generated by Xtext
*/
package eu.ddmore.pml.ui.contentassist;

import eu.ddmore.pml.ui.contentassist.AbstractPharmMLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class PharmMLProposalProvider extends AbstractPharmMLProposalProvider {

}
