/*
* generated by Xtext
*/
package eu.ddmore.mdl.tests;

import com.google.inject.Injector;

import eu.ddmore.mdl.tests.MdlInjectorProvider;
import eu.ddmore.mdllib.tests.MdlLibInjectorProvider;

public class MdlAndLibInjectorProvider extends MdlInjectorProvider{ 

	@Override
	protected Injector internalCreateInjector(){
		new MdlLibInjectorProvider().getInjector();
		return super.internalCreateInjector();
	}

}
