/*
* generated by Xtext
*/
package org.ddmore.pml;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PharmaMLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.ddmore.pml.ui.internal.PharmaMLActivator.getInstance().getInjector("org.ddmore.pml.PharmaML");
	}
	
}
