/*
 * generated by Xtext
 */
package org.ddmore.pml;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PharmaMLRuntimeModule extends org.ddmore.pml.AbstractPharmaMLRuntimeModule {

}
