package eu.ddmore.pml.serializer;

import com.google.inject.Inject;
import eu.ddmore.pml.services.PharmMLGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class PharmMLSyntacticSequencer extends AbstractSyntacticSequencer {

	protected PharmMLGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Math_ConstantType_TAG_CLOSE2ParserRuleCall_7_0_or___TAG_CLOSEParserRuleCall_7_1_0_TAG_OPEN2ParserRuleCall_7_1_1_ConstantKeyword_7_1_2_TAG_CLOSEParserRuleCall_7_1_3__;
	protected AbstractElementAlias match_Math_Otherwise_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_OtherwiseKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__;
	protected AbstractElementAlias match_Math_PiecewiseType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_PiecewiseKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__;
	protected AbstractElementAlias match_Math_ScalarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_ScalarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__;
	protected AbstractElementAlias match_Math_StringType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_StringKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__;
	protected AbstractElementAlias match_Math_VarType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_VarKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__;
	protected AbstractElementAlias match_Mml_FuncParameterDefinitionType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_2_FunctionArgumentKeyword_6_1_3_TAG_CLOSEParserRuleCall_6_1_4__;
	protected AbstractElementAlias match_XS_xmlns_XmlnsKeyword_0_0_or_XsiKeyword_0_1;
	protected AbstractElementAlias match_XS_xmlns___ColonKeyword_1_0___IDTerminalRuleCall_1_1_0_or_XsiKeyword_1_1_1____q;
	protected AbstractElementAlias match_ct_CellType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_CellKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__;
	protected AbstractElementAlias match_ct_ColumnType_TAG_CLOSE2ParserRuleCall_9_0_or___TAG_CLOSEParserRuleCall_9_1_0_TAG_OPEN2ParserRuleCall_9_1_1_ColumnKeyword_9_1_2_TAG_CLOSEParserRuleCall_9_1_3__;
	protected AbstractElementAlias match_ct_DefinitionRhsType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_DefinitionKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__;
	protected AbstractElementAlias match_ct_DefinitionType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_DefinitionKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__;
	protected AbstractElementAlias match_ct_ExternalSourceType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_ExternalSourceKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__;
	protected AbstractElementAlias match_ct_InternalSourceType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_InternalSourceKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__;
	protected AbstractElementAlias match_ct_ReplicatesType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_ReplicatesKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__;
	protected AbstractElementAlias match_ct_RestrictionType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_RestrictionKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__;
	protected AbstractElementAlias match_ct_RowType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_RowKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__;
	protected AbstractElementAlias match_ct_SequenceType_TAG_CLOSE2ParserRuleCall_11_0_or___TAG_CLOSEParserRuleCall_11_1_0_TAG_OPEN2ParserRuleCall_11_1_1_SequenceKeyword_11_1_2_TAG_CLOSEParserRuleCall_11_1_3__;
	protected AbstractElementAlias match_ct_VariableDefinitionType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_3_VariableKeyword_4_1_4_TAG_CLOSEParserRuleCall_4_1_5__;
	protected AbstractElementAlias match_ct_VectorType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_3_VectorKeyword_4_1_4_TAG_CLOSEParserRuleCall_4_1_5__;
	protected AbstractElementAlias match_design_DoseAmountType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_DoseAmountKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__;
	protected AbstractElementAlias match_design_DoseVarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_DoseVarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__;
	protected AbstractElementAlias match_design_DosingPeriodType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_DosingPeriodKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__;
	protected AbstractElementAlias match_design_DosingRegimenType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_3_DosingRegimenKeyword_4_1_4_TAG_CLOSEParserRuleCall_4_1_5__;
	protected AbstractElementAlias match_design_TargetVarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_TargetVarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__;
	protected AbstractElementAlias match_design_TreatmentEpochRefType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_TreatmentEpochRefKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__;
	protected AbstractElementAlias match_design_TreatmentRefType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_TreatmentRefKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__;
	protected AbstractElementAlias match_design_WashoutType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_WashoutKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__;
	protected AbstractElementAlias match_mSteps_VariableEstimateType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_4_VariableKeyword_4_1_5_TAG_CLOSEParserRuleCall_4_1_6__;
	protected AbstractElementAlias match_mdef_CategoricalType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_CategoricalKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__;
	protected AbstractElementAlias match_mdef_CategoryType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_2_CategoryKeyword_5_1_3_TAG_CLOSEParserRuleCall_5_1_4__;
	protected AbstractElementAlias match_mdef_CovariateVariabilityType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_3_CovariateKeyword_6_1_4_TAG_CLOSEParserRuleCall_6_1_5__;
	protected AbstractElementAlias match_mdef_ModelDefinitionType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_6_ModelDefinitionKeyword_4_1_7_TAG_CLOSEParserRuleCall_4_1_8__;
	protected AbstractElementAlias match_mdef_ObservationModelType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_3_ObservationModelKeyword_5_1_4_TAG_CLOSEParserRuleCall_5_1_5__;
	protected AbstractElementAlias match_mdef_Param1VarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_Param1VarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__;
	protected AbstractElementAlias match_mdef_Param2VarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_Param2VarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__;
	protected AbstractElementAlias match_mdef_ParameterType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_6_ParameterKeyword_6_1_7_TAG_CLOSEParserRuleCall_6_1_8__;
	protected AbstractElementAlias match_mdef_StructuralModelType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_6_StructuralModelKeyword_4_1_7_TAG_CLOSEParserRuleCall_4_1_8__;
	protected AbstractElementAlias match_mdef_VariabilityLevelDefnType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_VariabilityLevelKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__;
	protected AbstractElementAlias match_msteps_ColumnMappingType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_3_MappingKeyword_6_1_4_TAG_CLOSEParserRuleCall_6_1_5__;
	protected AbstractElementAlias match_msteps_DependantStepType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_DependantStepKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__;
	protected AbstractElementAlias match_msteps_EstimationOperationType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_EstimationOperationKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__;
	protected AbstractElementAlias match_msteps_InitialValueType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_2_InitialValueKeyword_5_1_3_TAG_CLOSEParserRuleCall_5_1_4__;
	protected AbstractElementAlias match_msteps_ParametersToEstimateType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_ParametersToEstimateKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__;
	protected AbstractElementAlias match_msteps_SimulationStep_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_6_SimulationStepKeyword_4_1_7_TAG_CLOSEParserRuleCall_4_1_8__;
	protected AbstractElementAlias match_msteps_StepType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_2_StepKeyword_6_1_3_TAG_CLOSEParserRuleCall_6_1_4__;
	protected AbstractElementAlias match_msteps_TargetVarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_TargetVarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__;
	protected AbstractElementAlias match_msteps_UseVariabilityLevel_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_UseVariabilityLevelKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__;
	protected AbstractElementAlias match_msteps_UseVariabilityNode_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_UseVariabilityNodeKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__;
	protected AbstractElementAlias match_uncert_ParameterDefinitionType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_FunctionParameterKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__;
	protected AbstractElementAlias match_uncert_StdDev_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_StdDevKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__;
	protected AbstractElementAlias match_uncert_Uniform_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_UniformKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (PharmMLGrammarAccess) access;
		match_Math_ConstantType_TAG_CLOSE2ParserRuleCall_7_0_or___TAG_CLOSEParserRuleCall_7_1_0_TAG_OPEN2ParserRuleCall_7_1_1_ConstantKeyword_7_1_2_TAG_CLOSEParserRuleCall_7_1_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMath_ConstantTypeAccess().getTAG_CLOSEParserRuleCall_7_1_0()), new TokenAlias(false, false, grammarAccess.getMath_ConstantTypeAccess().getTAG_OPEN2ParserRuleCall_7_1_1()), new TokenAlias(false, false, grammarAccess.getMath_ConstantTypeAccess().getConstantKeyword_7_1_2()), new TokenAlias(false, false, grammarAccess.getMath_ConstantTypeAccess().getTAG_CLOSEParserRuleCall_7_1_3())), new TokenAlias(false, false, grammarAccess.getMath_ConstantTypeAccess().getTAG_CLOSE2ParserRuleCall_7_0()));
		match_Math_Otherwise_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_OtherwiseKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMath_OtherwiseAccess().getTAG_CLOSEParserRuleCall_4_1_0()), new TokenAlias(false, false, grammarAccess.getMath_OtherwiseAccess().getTAG_OPEN2ParserRuleCall_4_1_1()), new TokenAlias(false, false, grammarAccess.getMath_OtherwiseAccess().getOtherwiseKeyword_4_1_2()), new TokenAlias(false, false, grammarAccess.getMath_OtherwiseAccess().getTAG_CLOSEParserRuleCall_4_1_3())), new TokenAlias(false, false, grammarAccess.getMath_OtherwiseAccess().getTAG_CLOSE2ParserRuleCall_4_0()));
		match_Math_PiecewiseType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_PiecewiseKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMath_PiecewiseTypeAccess().getTAG_CLOSEParserRuleCall_4_1_0()), new TokenAlias(false, false, grammarAccess.getMath_PiecewiseTypeAccess().getTAG_OPEN2ParserRuleCall_4_1_2()), new TokenAlias(false, false, grammarAccess.getMath_PiecewiseTypeAccess().getPiecewiseKeyword_4_1_3()), new TokenAlias(false, false, grammarAccess.getMath_PiecewiseTypeAccess().getTAG_CLOSEParserRuleCall_4_1_4())), new TokenAlias(false, false, grammarAccess.getMath_PiecewiseTypeAccess().getTAG_CLOSE2ParserRuleCall_4_0()));
		match_Math_ScalarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_ScalarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMath_ScalarTypeAccess().getTAG_CLOSEParserRuleCall_5_1_0()), new TokenAlias(false, false, grammarAccess.getMath_ScalarTypeAccess().getTAG_OPEN2ParserRuleCall_5_1_1()), new TokenAlias(false, false, grammarAccess.getMath_ScalarTypeAccess().getScalarKeyword_5_1_2()), new TokenAlias(false, false, grammarAccess.getMath_ScalarTypeAccess().getTAG_CLOSEParserRuleCall_5_1_3())), new TokenAlias(false, false, grammarAccess.getMath_ScalarTypeAccess().getTAG_CLOSE2ParserRuleCall_5_0()));
		match_Math_StringType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_StringKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMath_StringTypeAccess().getTAG_CLOSEParserRuleCall_4_1_0()), new TokenAlias(false, false, grammarAccess.getMath_StringTypeAccess().getTAG_OPEN2ParserRuleCall_4_1_1()), new TokenAlias(false, false, grammarAccess.getMath_StringTypeAccess().getStringKeyword_4_1_2()), new TokenAlias(false, false, grammarAccess.getMath_StringTypeAccess().getTAG_CLOSEParserRuleCall_4_1_3())), new TokenAlias(false, false, grammarAccess.getMath_StringTypeAccess().getTAG_CLOSE2ParserRuleCall_4_0()));
		match_Math_VarType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_VarKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMath_VarTypeAccess().getTAG_CLOSEParserRuleCall_6_1_0()), new TokenAlias(false, false, grammarAccess.getMath_VarTypeAccess().getTAG_OPEN2ParserRuleCall_6_1_1()), new TokenAlias(false, false, grammarAccess.getMath_VarTypeAccess().getVarKeyword_6_1_2()), new TokenAlias(false, false, grammarAccess.getMath_VarTypeAccess().getTAG_CLOSEParserRuleCall_6_1_3())), new TokenAlias(false, false, grammarAccess.getMath_VarTypeAccess().getTAG_CLOSE2ParserRuleCall_6_0()));
		match_Mml_FuncParameterDefinitionType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_2_FunctionArgumentKeyword_6_1_3_TAG_CLOSEParserRuleCall_6_1_4__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMml_FuncParameterDefinitionTypeAccess().getTAG_CLOSEParserRuleCall_6_1_0()), new TokenAlias(false, false, grammarAccess.getMml_FuncParameterDefinitionTypeAccess().getTAG_OPEN2ParserRuleCall_6_1_2()), new TokenAlias(false, false, grammarAccess.getMml_FuncParameterDefinitionTypeAccess().getFunctionArgumentKeyword_6_1_3()), new TokenAlias(false, false, grammarAccess.getMml_FuncParameterDefinitionTypeAccess().getTAG_CLOSEParserRuleCall_6_1_4())), new TokenAlias(false, false, grammarAccess.getMml_FuncParameterDefinitionTypeAccess().getTAG_CLOSE2ParserRuleCall_6_0()));
		match_XS_xmlns_XmlnsKeyword_0_0_or_XsiKeyword_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getXS_xmlnsAccess().getXmlnsKeyword_0_0()), new TokenAlias(false, false, grammarAccess.getXS_xmlnsAccess().getXsiKeyword_0_1()));
		match_XS_xmlns___ColonKeyword_1_0___IDTerminalRuleCall_1_1_0_or_XsiKeyword_1_1_1____q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getXS_xmlnsAccess().getColonKeyword_1_0()), new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getXS_xmlnsAccess().getIDTerminalRuleCall_1_1_0()), new TokenAlias(false, false, grammarAccess.getXS_xmlnsAccess().getXsiKeyword_1_1_1())));
		match_ct_CellType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_CellKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getCt_CellTypeAccess().getTAG_CLOSEParserRuleCall_4_1_0()), new TokenAlias(false, false, grammarAccess.getCt_CellTypeAccess().getTAG_OPEN2ParserRuleCall_4_1_1()), new TokenAlias(false, false, grammarAccess.getCt_CellTypeAccess().getCellKeyword_4_1_2()), new TokenAlias(false, false, grammarAccess.getCt_CellTypeAccess().getTAG_CLOSEParserRuleCall_4_1_3())), new TokenAlias(false, false, grammarAccess.getCt_CellTypeAccess().getTAG_CLOSE2ParserRuleCall_4_0()));
		match_ct_ColumnType_TAG_CLOSE2ParserRuleCall_9_0_or___TAG_CLOSEParserRuleCall_9_1_0_TAG_OPEN2ParserRuleCall_9_1_1_ColumnKeyword_9_1_2_TAG_CLOSEParserRuleCall_9_1_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getCt_ColumnTypeAccess().getTAG_CLOSEParserRuleCall_9_1_0()), new TokenAlias(false, false, grammarAccess.getCt_ColumnTypeAccess().getTAG_OPEN2ParserRuleCall_9_1_1()), new TokenAlias(false, false, grammarAccess.getCt_ColumnTypeAccess().getColumnKeyword_9_1_2()), new TokenAlias(false, false, grammarAccess.getCt_ColumnTypeAccess().getTAG_CLOSEParserRuleCall_9_1_3())), new TokenAlias(false, false, grammarAccess.getCt_ColumnTypeAccess().getTAG_CLOSE2ParserRuleCall_9_0()));
		match_ct_DefinitionRhsType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_DefinitionKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getCt_DefinitionRhsTypeAccess().getTAG_CLOSEParserRuleCall_4_1_0()), new TokenAlias(false, false, grammarAccess.getCt_DefinitionRhsTypeAccess().getTAG_OPEN2ParserRuleCall_4_1_2()), new TokenAlias(false, false, grammarAccess.getCt_DefinitionRhsTypeAccess().getDefinitionKeyword_4_1_3()), new TokenAlias(false, false, grammarAccess.getCt_DefinitionRhsTypeAccess().getTAG_CLOSEParserRuleCall_4_1_4())), new TokenAlias(false, false, grammarAccess.getCt_DefinitionRhsTypeAccess().getTAG_CLOSE2ParserRuleCall_4_0()));
		match_ct_DefinitionType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_DefinitionKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getCt_DefinitionTypeAccess().getTAG_CLOSEParserRuleCall_4_1_0()), new TokenAlias(false, false, grammarAccess.getCt_DefinitionTypeAccess().getTAG_OPEN2ParserRuleCall_4_1_2()), new TokenAlias(false, false, grammarAccess.getCt_DefinitionTypeAccess().getDefinitionKeyword_4_1_3()), new TokenAlias(false, false, grammarAccess.getCt_DefinitionTypeAccess().getTAG_CLOSEParserRuleCall_4_1_4())), new TokenAlias(false, false, grammarAccess.getCt_DefinitionTypeAccess().getTAG_CLOSE2ParserRuleCall_4_0()));
		match_ct_ExternalSourceType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_ExternalSourceKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getCt_ExternalSourceTypeAccess().getTAG_CLOSEParserRuleCall_4_1_0()), new TokenAlias(false, false, grammarAccess.getCt_ExternalSourceTypeAccess().getTAG_OPEN2ParserRuleCall_4_1_1()), new TokenAlias(false, false, grammarAccess.getCt_ExternalSourceTypeAccess().getExternalSourceKeyword_4_1_2()), new TokenAlias(false, false, grammarAccess.getCt_ExternalSourceTypeAccess().getTAG_CLOSEParserRuleCall_4_1_3())), new TokenAlias(false, false, grammarAccess.getCt_ExternalSourceTypeAccess().getTAG_CLOSE2ParserRuleCall_4_0()));
		match_ct_InternalSourceType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_InternalSourceKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getCt_InternalSourceTypeAccess().getTAG_CLOSEParserRuleCall_5_1_0()), new TokenAlias(false, false, grammarAccess.getCt_InternalSourceTypeAccess().getTAG_OPEN2ParserRuleCall_5_1_1()), new TokenAlias(false, false, grammarAccess.getCt_InternalSourceTypeAccess().getInternalSourceKeyword_5_1_2()), new TokenAlias(false, false, grammarAccess.getCt_InternalSourceTypeAccess().getTAG_CLOSEParserRuleCall_5_1_3())), new TokenAlias(false, false, grammarAccess.getCt_InternalSourceTypeAccess().getTAG_CLOSE2ParserRuleCall_5_0()));
		match_ct_ReplicatesType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_ReplicatesKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getCt_ReplicatesTypeAccess().getTAG_CLOSEParserRuleCall_4_1_0()), new TokenAlias(false, false, grammarAccess.getCt_ReplicatesTypeAccess().getTAG_OPEN2ParserRuleCall_4_1_2()), new TokenAlias(false, false, grammarAccess.getCt_ReplicatesTypeAccess().getReplicatesKeyword_4_1_3()), new TokenAlias(false, false, grammarAccess.getCt_ReplicatesTypeAccess().getTAG_CLOSEParserRuleCall_4_1_4())), new TokenAlias(false, false, grammarAccess.getCt_ReplicatesTypeAccess().getTAG_CLOSE2ParserRuleCall_4_0()));
		match_ct_RestrictionType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_RestrictionKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getCt_RestrictionTypeAccess().getTAG_CLOSEParserRuleCall_4_1_0()), new TokenAlias(false, false, grammarAccess.getCt_RestrictionTypeAccess().getTAG_OPEN2ParserRuleCall_4_1_2()), new TokenAlias(false, false, grammarAccess.getCt_RestrictionTypeAccess().getRestrictionKeyword_4_1_3()), new TokenAlias(false, false, grammarAccess.getCt_RestrictionTypeAccess().getTAG_CLOSEParserRuleCall_4_1_4())), new TokenAlias(false, false, grammarAccess.getCt_RestrictionTypeAccess().getTAG_CLOSE2ParserRuleCall_4_0()));
		match_ct_RowType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_RowKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getCt_RowTypeAccess().getTAG_CLOSEParserRuleCall_4_1_0()), new TokenAlias(false, false, grammarAccess.getCt_RowTypeAccess().getTAG_OPEN2ParserRuleCall_4_1_2()), new TokenAlias(false, false, grammarAccess.getCt_RowTypeAccess().getRowKeyword_4_1_3()), new TokenAlias(false, false, grammarAccess.getCt_RowTypeAccess().getTAG_CLOSEParserRuleCall_4_1_4())), new TokenAlias(false, false, grammarAccess.getCt_RowTypeAccess().getTAG_CLOSE2ParserRuleCall_4_0()));
		match_ct_SequenceType_TAG_CLOSE2ParserRuleCall_11_0_or___TAG_CLOSEParserRuleCall_11_1_0_TAG_OPEN2ParserRuleCall_11_1_1_SequenceKeyword_11_1_2_TAG_CLOSEParserRuleCall_11_1_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getCt_SequenceTypeAccess().getTAG_CLOSEParserRuleCall_11_1_0()), new TokenAlias(false, false, grammarAccess.getCt_SequenceTypeAccess().getTAG_OPEN2ParserRuleCall_11_1_1()), new TokenAlias(false, false, grammarAccess.getCt_SequenceTypeAccess().getSequenceKeyword_11_1_2()), new TokenAlias(false, false, grammarAccess.getCt_SequenceTypeAccess().getTAG_CLOSEParserRuleCall_11_1_3())), new TokenAlias(false, false, grammarAccess.getCt_SequenceTypeAccess().getTAG_CLOSE2ParserRuleCall_11_0()));
		match_ct_VariableDefinitionType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_3_VariableKeyword_4_1_4_TAG_CLOSEParserRuleCall_4_1_5__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getCt_VariableDefinitionTypeAccess().getTAG_CLOSEParserRuleCall_4_1_0()), new TokenAlias(false, false, grammarAccess.getCt_VariableDefinitionTypeAccess().getTAG_OPEN2ParserRuleCall_4_1_3()), new TokenAlias(false, false, grammarAccess.getCt_VariableDefinitionTypeAccess().getVariableKeyword_4_1_4()), new TokenAlias(false, false, grammarAccess.getCt_VariableDefinitionTypeAccess().getTAG_CLOSEParserRuleCall_4_1_5())), new TokenAlias(false, false, grammarAccess.getCt_VariableDefinitionTypeAccess().getTAG_CLOSE2ParserRuleCall_4_0()));
		match_ct_VectorType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_3_VectorKeyword_4_1_4_TAG_CLOSEParserRuleCall_4_1_5__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getCt_VectorTypeAccess().getTAG_CLOSEParserRuleCall_4_1_0()), new TokenAlias(false, false, grammarAccess.getCt_VectorTypeAccess().getTAG_OPEN2ParserRuleCall_4_1_3()), new TokenAlias(false, false, grammarAccess.getCt_VectorTypeAccess().getVectorKeyword_4_1_4()), new TokenAlias(false, false, grammarAccess.getCt_VectorTypeAccess().getTAG_CLOSEParserRuleCall_4_1_5())), new TokenAlias(false, false, grammarAccess.getCt_VectorTypeAccess().getTAG_CLOSE2ParserRuleCall_4_0()));
		match_design_DoseAmountType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_DoseAmountKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getDesign_DoseAmountTypeAccess().getTAG_CLOSEParserRuleCall_4_1_0()), new TokenAlias(false, false, grammarAccess.getDesign_DoseAmountTypeAccess().getTAG_OPEN2ParserRuleCall_4_1_2()), new TokenAlias(false, false, grammarAccess.getDesign_DoseAmountTypeAccess().getDoseAmountKeyword_4_1_3()), new TokenAlias(false, false, grammarAccess.getDesign_DoseAmountTypeAccess().getTAG_CLOSEParserRuleCall_4_1_4())), new TokenAlias(false, false, grammarAccess.getDesign_DoseAmountTypeAccess().getTAG_CLOSE2ParserRuleCall_4_0()));
		match_design_DoseVarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_DoseVarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getDesign_DoseVarTypeAccess().getTAG_CLOSEParserRuleCall_5_1_0()), new TokenAlias(false, false, grammarAccess.getDesign_DoseVarTypeAccess().getTAG_OPEN2ParserRuleCall_5_1_1()), new TokenAlias(false, false, grammarAccess.getDesign_DoseVarTypeAccess().getDoseVarKeyword_5_1_2()), new TokenAlias(false, false, grammarAccess.getDesign_DoseVarTypeAccess().getTAG_CLOSEParserRuleCall_5_1_3())), new TokenAlias(false, false, grammarAccess.getDesign_DoseVarTypeAccess().getTAG_CLOSE2ParserRuleCall_5_0()));
		match_design_DosingPeriodType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_DosingPeriodKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getDesign_DosingPeriodTypeAccess().getTAG_CLOSEParserRuleCall_4_1_0()), new TokenAlias(false, false, grammarAccess.getDesign_DosingPeriodTypeAccess().getTAG_OPEN2ParserRuleCall_4_1_2()), new TokenAlias(false, false, grammarAccess.getDesign_DosingPeriodTypeAccess().getDosingPeriodKeyword_4_1_3()), new TokenAlias(false, false, grammarAccess.getDesign_DosingPeriodTypeAccess().getTAG_CLOSEParserRuleCall_4_1_4())), new TokenAlias(false, false, grammarAccess.getDesign_DosingPeriodTypeAccess().getTAG_CLOSE2ParserRuleCall_4_0()));
		match_design_DosingRegimenType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_3_DosingRegimenKeyword_4_1_4_TAG_CLOSEParserRuleCall_4_1_5__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getDesign_DosingRegimenTypeAccess().getTAG_CLOSEParserRuleCall_4_1_0()), new TokenAlias(false, false, grammarAccess.getDesign_DosingRegimenTypeAccess().getTAG_OPEN2ParserRuleCall_4_1_3()), new TokenAlias(false, false, grammarAccess.getDesign_DosingRegimenTypeAccess().getDosingRegimenKeyword_4_1_4()), new TokenAlias(false, false, grammarAccess.getDesign_DosingRegimenTypeAccess().getTAG_CLOSEParserRuleCall_4_1_5())), new TokenAlias(false, false, grammarAccess.getDesign_DosingRegimenTypeAccess().getTAG_CLOSE2ParserRuleCall_4_0()));
		match_design_TargetVarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_TargetVarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getDesign_TargetVarTypeAccess().getTAG_CLOSEParserRuleCall_5_1_0()), new TokenAlias(false, false, grammarAccess.getDesign_TargetVarTypeAccess().getTAG_OPEN2ParserRuleCall_5_1_1()), new TokenAlias(false, false, grammarAccess.getDesign_TargetVarTypeAccess().getTargetVarKeyword_5_1_2()), new TokenAlias(false, false, grammarAccess.getDesign_TargetVarTypeAccess().getTAG_CLOSEParserRuleCall_5_1_3())), new TokenAlias(false, false, grammarAccess.getDesign_TargetVarTypeAccess().getTAG_CLOSE2ParserRuleCall_5_0()));
		match_design_TreatmentEpochRefType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_TreatmentEpochRefKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getDesign_TreatmentEpochRefTypeAccess().getTAG_CLOSEParserRuleCall_6_1_0()), new TokenAlias(false, false, grammarAccess.getDesign_TreatmentEpochRefTypeAccess().getTAG_OPEN2ParserRuleCall_6_1_1()), new TokenAlias(false, false, grammarAccess.getDesign_TreatmentEpochRefTypeAccess().getTreatmentEpochRefKeyword_6_1_2()), new TokenAlias(false, false, grammarAccess.getDesign_TreatmentEpochRefTypeAccess().getTAG_CLOSEParserRuleCall_6_1_3())), new TokenAlias(false, false, grammarAccess.getDesign_TreatmentEpochRefTypeAccess().getTAG_CLOSE2ParserRuleCall_6_0()));
		match_design_TreatmentRefType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_TreatmentRefKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getDesign_TreatmentRefTypeAccess().getTAG_CLOSEParserRuleCall_6_1_0()), new TokenAlias(false, false, grammarAccess.getDesign_TreatmentRefTypeAccess().getTAG_OPEN2ParserRuleCall_6_1_1()), new TokenAlias(false, false, grammarAccess.getDesign_TreatmentRefTypeAccess().getTreatmentRefKeyword_6_1_2()), new TokenAlias(false, false, grammarAccess.getDesign_TreatmentRefTypeAccess().getTAG_CLOSEParserRuleCall_6_1_3())), new TokenAlias(false, false, grammarAccess.getDesign_TreatmentRefTypeAccess().getTAG_CLOSE2ParserRuleCall_6_0()));
		match_design_WashoutType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_WashoutKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getDesign_WashoutTypeAccess().getTAG_CLOSEParserRuleCall_4_1_0()), new TokenAlias(false, false, grammarAccess.getDesign_WashoutTypeAccess().getTAG_OPEN2ParserRuleCall_4_1_1()), new TokenAlias(false, false, grammarAccess.getDesign_WashoutTypeAccess().getWashoutKeyword_4_1_2()), new TokenAlias(false, false, grammarAccess.getDesign_WashoutTypeAccess().getTAG_CLOSEParserRuleCall_4_1_3())), new TokenAlias(false, false, grammarAccess.getDesign_WashoutTypeAccess().getTAG_CLOSE2ParserRuleCall_4_0()));
		match_mSteps_VariableEstimateType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_4_VariableKeyword_4_1_5_TAG_CLOSEParserRuleCall_4_1_6__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMSteps_VariableEstimateTypeAccess().getTAG_CLOSEParserRuleCall_4_1_0()), new TokenAlias(false, false, grammarAccess.getMSteps_VariableEstimateTypeAccess().getTAG_OPEN2ParserRuleCall_4_1_4()), new TokenAlias(false, false, grammarAccess.getMSteps_VariableEstimateTypeAccess().getVariableKeyword_4_1_5()), new TokenAlias(false, false, grammarAccess.getMSteps_VariableEstimateTypeAccess().getTAG_CLOSEParserRuleCall_4_1_6())), new TokenAlias(false, false, grammarAccess.getMSteps_VariableEstimateTypeAccess().getTAG_CLOSE2ParserRuleCall_4_0()));
		match_mdef_CategoricalType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_CategoricalKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMdef_CategoricalTypeAccess().getTAG_CLOSEParserRuleCall_4_1_0()), new TokenAlias(false, false, grammarAccess.getMdef_CategoricalTypeAccess().getTAG_OPEN2ParserRuleCall_4_1_2()), new TokenAlias(false, false, grammarAccess.getMdef_CategoricalTypeAccess().getCategoricalKeyword_4_1_3()), new TokenAlias(false, false, grammarAccess.getMdef_CategoricalTypeAccess().getTAG_CLOSEParserRuleCall_4_1_4())), new TokenAlias(false, false, grammarAccess.getMdef_CategoricalTypeAccess().getTAG_CLOSE2ParserRuleCall_4_0()));
		match_mdef_CategoryType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_2_CategoryKeyword_5_1_3_TAG_CLOSEParserRuleCall_5_1_4__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMdef_CategoryTypeAccess().getTAG_CLOSEParserRuleCall_5_1_0()), new TokenAlias(false, false, grammarAccess.getMdef_CategoryTypeAccess().getTAG_OPEN2ParserRuleCall_5_1_2()), new TokenAlias(false, false, grammarAccess.getMdef_CategoryTypeAccess().getCategoryKeyword_5_1_3()), new TokenAlias(false, false, grammarAccess.getMdef_CategoryTypeAccess().getTAG_CLOSEParserRuleCall_5_1_4())), new TokenAlias(false, false, grammarAccess.getMdef_CategoryTypeAccess().getTAG_CLOSE2ParserRuleCall_5_0()));
		match_mdef_CovariateVariabilityType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_3_CovariateKeyword_6_1_4_TAG_CLOSEParserRuleCall_6_1_5__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMdef_CovariateVariabilityTypeAccess().getTAG_CLOSEParserRuleCall_6_1_0()), new TokenAlias(false, false, grammarAccess.getMdef_CovariateVariabilityTypeAccess().getTAG_OPEN2ParserRuleCall_6_1_3()), new TokenAlias(false, false, grammarAccess.getMdef_CovariateVariabilityTypeAccess().getCovariateKeyword_6_1_4()), new TokenAlias(false, false, grammarAccess.getMdef_CovariateVariabilityTypeAccess().getTAG_CLOSEParserRuleCall_6_1_5())), new TokenAlias(false, false, grammarAccess.getMdef_CovariateVariabilityTypeAccess().getTAG_CLOSE2ParserRuleCall_6_0()));
		match_mdef_ModelDefinitionType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_6_ModelDefinitionKeyword_4_1_7_TAG_CLOSEParserRuleCall_4_1_8__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMdef_ModelDefinitionTypeAccess().getTAG_CLOSEParserRuleCall_4_1_0()), new TokenAlias(false, false, grammarAccess.getMdef_ModelDefinitionTypeAccess().getTAG_OPEN2ParserRuleCall_4_1_6()), new TokenAlias(false, false, grammarAccess.getMdef_ModelDefinitionTypeAccess().getModelDefinitionKeyword_4_1_7()), new TokenAlias(false, false, grammarAccess.getMdef_ModelDefinitionTypeAccess().getTAG_CLOSEParserRuleCall_4_1_8())), new TokenAlias(false, false, grammarAccess.getMdef_ModelDefinitionTypeAccess().getTAG_CLOSE2ParserRuleCall_4_0()));
		match_mdef_ObservationModelType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_3_ObservationModelKeyword_5_1_4_TAG_CLOSEParserRuleCall_5_1_5__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMdef_ObservationModelTypeAccess().getTAG_CLOSEParserRuleCall_5_1_0()), new TokenAlias(false, false, grammarAccess.getMdef_ObservationModelTypeAccess().getTAG_OPEN2ParserRuleCall_5_1_3()), new TokenAlias(false, false, grammarAccess.getMdef_ObservationModelTypeAccess().getObservationModelKeyword_5_1_4()), new TokenAlias(false, false, grammarAccess.getMdef_ObservationModelTypeAccess().getTAG_CLOSEParserRuleCall_5_1_5())), new TokenAlias(false, false, grammarAccess.getMdef_ObservationModelTypeAccess().getTAG_CLOSE2ParserRuleCall_5_0()));
		match_mdef_Param1VarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_Param1VarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMdef_Param1VarTypeAccess().getTAG_CLOSEParserRuleCall_5_1_0()), new TokenAlias(false, false, grammarAccess.getMdef_Param1VarTypeAccess().getTAG_OPEN2ParserRuleCall_5_1_1()), new TokenAlias(false, false, grammarAccess.getMdef_Param1VarTypeAccess().getParam1VarKeyword_5_1_2()), new TokenAlias(false, false, grammarAccess.getMdef_Param1VarTypeAccess().getTAG_CLOSEParserRuleCall_5_1_3())), new TokenAlias(false, false, grammarAccess.getMdef_Param1VarTypeAccess().getTAG_CLOSE2ParserRuleCall_5_0()));
		match_mdef_Param2VarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_Param2VarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMdef_Param2VarTypeAccess().getTAG_CLOSEParserRuleCall_5_1_0()), new TokenAlias(false, false, grammarAccess.getMdef_Param2VarTypeAccess().getTAG_OPEN2ParserRuleCall_5_1_1()), new TokenAlias(false, false, grammarAccess.getMdef_Param2VarTypeAccess().getParam2VarKeyword_5_1_2()), new TokenAlias(false, false, grammarAccess.getMdef_Param2VarTypeAccess().getTAG_CLOSEParserRuleCall_5_1_3())), new TokenAlias(false, false, grammarAccess.getMdef_Param2VarTypeAccess().getTAG_CLOSE2ParserRuleCall_5_0()));
		match_mdef_ParameterType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_6_ParameterKeyword_6_1_7_TAG_CLOSEParserRuleCall_6_1_8__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMdef_ParameterTypeAccess().getTAG_CLOSEParserRuleCall_6_1_0()), new TokenAlias(false, false, grammarAccess.getMdef_ParameterTypeAccess().getTAG_OPEN2ParserRuleCall_6_1_6()), new TokenAlias(false, false, grammarAccess.getMdef_ParameterTypeAccess().getParameterKeyword_6_1_7()), new TokenAlias(false, false, grammarAccess.getMdef_ParameterTypeAccess().getTAG_CLOSEParserRuleCall_6_1_8())), new TokenAlias(false, false, grammarAccess.getMdef_ParameterTypeAccess().getTAG_CLOSE2ParserRuleCall_6_0()));
		match_mdef_StructuralModelType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_6_StructuralModelKeyword_4_1_7_TAG_CLOSEParserRuleCall_4_1_8__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMdef_StructuralModelTypeAccess().getTAG_CLOSEParserRuleCall_4_1_0()), new TokenAlias(false, false, grammarAccess.getMdef_StructuralModelTypeAccess().getTAG_OPEN2ParserRuleCall_4_1_6()), new TokenAlias(false, false, grammarAccess.getMdef_StructuralModelTypeAccess().getStructuralModelKeyword_4_1_7()), new TokenAlias(false, false, grammarAccess.getMdef_StructuralModelTypeAccess().getTAG_CLOSEParserRuleCall_4_1_8())), new TokenAlias(false, false, grammarAccess.getMdef_StructuralModelTypeAccess().getTAG_CLOSE2ParserRuleCall_4_0()));
		match_mdef_VariabilityLevelDefnType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_VariabilityLevelKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMdef_VariabilityLevelDefnTypeAccess().getTAG_CLOSEParserRuleCall_5_1_0()), new TokenAlias(false, false, grammarAccess.getMdef_VariabilityLevelDefnTypeAccess().getTAG_OPEN2ParserRuleCall_5_1_1()), new TokenAlias(false, false, grammarAccess.getMdef_VariabilityLevelDefnTypeAccess().getVariabilityLevelKeyword_5_1_2()), new TokenAlias(false, false, grammarAccess.getMdef_VariabilityLevelDefnTypeAccess().getTAG_CLOSEParserRuleCall_5_1_3())), new TokenAlias(false, false, grammarAccess.getMdef_VariabilityLevelDefnTypeAccess().getTAG_CLOSE2ParserRuleCall_5_0()));
		match_msteps_ColumnMappingType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_3_MappingKeyword_6_1_4_TAG_CLOSEParserRuleCall_6_1_5__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMsteps_ColumnMappingTypeAccess().getTAG_CLOSEParserRuleCall_6_1_0()), new TokenAlias(false, false, grammarAccess.getMsteps_ColumnMappingTypeAccess().getTAG_OPEN2ParserRuleCall_6_1_3()), new TokenAlias(false, false, grammarAccess.getMsteps_ColumnMappingTypeAccess().getMappingKeyword_6_1_4()), new TokenAlias(false, false, grammarAccess.getMsteps_ColumnMappingTypeAccess().getTAG_CLOSEParserRuleCall_6_1_5())), new TokenAlias(false, false, grammarAccess.getMsteps_ColumnMappingTypeAccess().getTAG_CLOSE2ParserRuleCall_6_0()));
		match_msteps_DependantStepType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_DependantStepKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMsteps_DependantStepTypeAccess().getTAG_CLOSEParserRuleCall_6_1_0()), new TokenAlias(false, false, grammarAccess.getMsteps_DependantStepTypeAccess().getTAG_OPEN2ParserRuleCall_6_1_1()), new TokenAlias(false, false, grammarAccess.getMsteps_DependantStepTypeAccess().getDependantStepKeyword_6_1_2()), new TokenAlias(false, false, grammarAccess.getMsteps_DependantStepTypeAccess().getTAG_CLOSEParserRuleCall_6_1_3())), new TokenAlias(false, false, grammarAccess.getMsteps_DependantStepTypeAccess().getTAG_CLOSE2ParserRuleCall_6_0()));
		match_msteps_EstimationOperationType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_EstimationOperationKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMsteps_EstimationOperationTypeAccess().getTAG_CLOSEParserRuleCall_6_1_0()), new TokenAlias(false, false, grammarAccess.getMsteps_EstimationOperationTypeAccess().getTAG_OPEN2ParserRuleCall_6_1_1()), new TokenAlias(false, false, grammarAccess.getMsteps_EstimationOperationTypeAccess().getEstimationOperationKeyword_6_1_2()), new TokenAlias(false, false, grammarAccess.getMsteps_EstimationOperationTypeAccess().getTAG_CLOSEParserRuleCall_6_1_3())), new TokenAlias(false, false, grammarAccess.getMsteps_EstimationOperationTypeAccess().getTAG_CLOSE2ParserRuleCall_6_0()));
		match_msteps_InitialValueType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_2_InitialValueKeyword_5_1_3_TAG_CLOSEParserRuleCall_5_1_4__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMsteps_InitialValueTypeAccess().getTAG_CLOSEParserRuleCall_5_1_0()), new TokenAlias(false, false, grammarAccess.getMsteps_InitialValueTypeAccess().getTAG_OPEN2ParserRuleCall_5_1_2()), new TokenAlias(false, false, grammarAccess.getMsteps_InitialValueTypeAccess().getInitialValueKeyword_5_1_3()), new TokenAlias(false, false, grammarAccess.getMsteps_InitialValueTypeAccess().getTAG_CLOSEParserRuleCall_5_1_4())), new TokenAlias(false, false, grammarAccess.getMsteps_InitialValueTypeAccess().getTAG_CLOSE2ParserRuleCall_5_0()));
		match_msteps_ParametersToEstimateType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_ParametersToEstimateKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMsteps_ParametersToEstimateTypeAccess().getTAG_CLOSEParserRuleCall_4_1_0()), new TokenAlias(false, false, grammarAccess.getMsteps_ParametersToEstimateTypeAccess().getTAG_OPEN2ParserRuleCall_4_1_2()), new TokenAlias(false, false, grammarAccess.getMsteps_ParametersToEstimateTypeAccess().getParametersToEstimateKeyword_4_1_3()), new TokenAlias(false, false, grammarAccess.getMsteps_ParametersToEstimateTypeAccess().getTAG_CLOSEParserRuleCall_4_1_4())), new TokenAlias(false, false, grammarAccess.getMsteps_ParametersToEstimateTypeAccess().getTAG_CLOSE2ParserRuleCall_4_0()));
		match_msteps_SimulationStep_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_6_SimulationStepKeyword_4_1_7_TAG_CLOSEParserRuleCall_4_1_8__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMsteps_SimulationStepAccess().getTAG_CLOSEParserRuleCall_4_1_0()), new TokenAlias(false, false, grammarAccess.getMsteps_SimulationStepAccess().getTAG_OPEN2ParserRuleCall_4_1_6()), new TokenAlias(false, false, grammarAccess.getMsteps_SimulationStepAccess().getSimulationStepKeyword_4_1_7()), new TokenAlias(false, false, grammarAccess.getMsteps_SimulationStepAccess().getTAG_CLOSEParserRuleCall_4_1_8())), new TokenAlias(false, false, grammarAccess.getMsteps_SimulationStepAccess().getTAG_CLOSE2ParserRuleCall_4_0()));
		match_msteps_StepType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_2_StepKeyword_6_1_3_TAG_CLOSEParserRuleCall_6_1_4__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMsteps_StepTypeAccess().getTAG_CLOSEParserRuleCall_6_1_0()), new TokenAlias(false, false, grammarAccess.getMsteps_StepTypeAccess().getTAG_OPEN2ParserRuleCall_6_1_2()), new TokenAlias(false, false, grammarAccess.getMsteps_StepTypeAccess().getStepKeyword_6_1_3()), new TokenAlias(false, false, grammarAccess.getMsteps_StepTypeAccess().getTAG_CLOSEParserRuleCall_6_1_4())), new TokenAlias(false, false, grammarAccess.getMsteps_StepTypeAccess().getTAG_CLOSE2ParserRuleCall_6_0()));
		match_msteps_TargetVarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_TargetVarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMsteps_TargetVarTypeAccess().getTAG_CLOSEParserRuleCall_5_1_0()), new TokenAlias(false, false, grammarAccess.getMsteps_TargetVarTypeAccess().getTAG_OPEN2ParserRuleCall_5_1_1()), new TokenAlias(false, false, grammarAccess.getMsteps_TargetVarTypeAccess().getTargetVarKeyword_5_1_2()), new TokenAlias(false, false, grammarAccess.getMsteps_TargetVarTypeAccess().getTAG_CLOSEParserRuleCall_5_1_3())), new TokenAlias(false, false, grammarAccess.getMsteps_TargetVarTypeAccess().getTAG_CLOSE2ParserRuleCall_5_0()));
		match_msteps_UseVariabilityLevel_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_UseVariabilityLevelKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMsteps_UseVariabilityLevelAccess().getTAG_CLOSEParserRuleCall_6_1_0()), new TokenAlias(false, false, grammarAccess.getMsteps_UseVariabilityLevelAccess().getTAG_OPEN2ParserRuleCall_6_1_1()), new TokenAlias(false, false, grammarAccess.getMsteps_UseVariabilityLevelAccess().getUseVariabilityLevelKeyword_6_1_2()), new TokenAlias(false, false, grammarAccess.getMsteps_UseVariabilityLevelAccess().getTAG_CLOSEParserRuleCall_6_1_3())), new TokenAlias(false, false, grammarAccess.getMsteps_UseVariabilityLevelAccess().getTAG_CLOSE2ParserRuleCall_6_0()));
		match_msteps_UseVariabilityNode_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_UseVariabilityNodeKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getMsteps_UseVariabilityNodeAccess().getTAG_CLOSEParserRuleCall_5_1_0()), new TokenAlias(false, false, grammarAccess.getMsteps_UseVariabilityNodeAccess().getTAG_OPEN2ParserRuleCall_5_1_1()), new TokenAlias(false, false, grammarAccess.getMsteps_UseVariabilityNodeAccess().getUseVariabilityNodeKeyword_5_1_2()), new TokenAlias(false, false, grammarAccess.getMsteps_UseVariabilityNodeAccess().getTAG_CLOSEParserRuleCall_5_1_3())), new TokenAlias(false, false, grammarAccess.getMsteps_UseVariabilityNodeAccess().getTAG_CLOSE2ParserRuleCall_5_0()));
		match_uncert_ParameterDefinitionType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_FunctionParameterKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getUncert_ParameterDefinitionTypeAccess().getTAG_CLOSEParserRuleCall_5_1_0()), new TokenAlias(false, false, grammarAccess.getUncert_ParameterDefinitionTypeAccess().getTAG_OPEN2ParserRuleCall_5_1_1()), new TokenAlias(false, false, grammarAccess.getUncert_ParameterDefinitionTypeAccess().getFunctionParameterKeyword_5_1_2()), new TokenAlias(false, false, grammarAccess.getUncert_ParameterDefinitionTypeAccess().getTAG_CLOSEParserRuleCall_5_1_3())), new TokenAlias(false, false, grammarAccess.getUncert_ParameterDefinitionTypeAccess().getTAG_CLOSE2ParserRuleCall_5_0()));
		match_uncert_StdDev_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_StdDevKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getUncert_StdDevAccess().getTAG_CLOSEParserRuleCall_4_1_0()), new TokenAlias(false, false, grammarAccess.getUncert_StdDevAccess().getTAG_OPEN2ParserRuleCall_4_1_2()), new TokenAlias(false, false, grammarAccess.getUncert_StdDevAccess().getStdDevKeyword_4_1_3()), new TokenAlias(false, false, grammarAccess.getUncert_StdDevAccess().getTAG_CLOSEParserRuleCall_4_1_4())), new TokenAlias(false, false, grammarAccess.getUncert_StdDevAccess().getTAG_CLOSE2ParserRuleCall_4_0()));
		match_uncert_Uniform_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_UniformKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getUncert_UniformAccess().getTAG_CLOSEParserRuleCall_4_1_0()), new TokenAlias(false, false, grammarAccess.getUncert_UniformAccess().getTAG_OPEN2ParserRuleCall_4_1_1()), new TokenAlias(false, false, grammarAccess.getUncert_UniformAccess().getUniformKeyword_4_1_2()), new TokenAlias(false, false, grammarAccess.getUncert_UniformAccess().getTAG_CLOSEParserRuleCall_4_1_3())), new TokenAlias(false, false, grammarAccess.getUncert_UniformAccess().getTAG_CLOSE2ParserRuleCall_4_0()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if(ruleCall.getRule() == grammarAccess.getIDRule())
			return getIDToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getTAG_CLOSERule())
			return getTAG_CLOSEToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getTAG_CLOSE2Rule())
			return getTAG_CLOSE2Token(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getTAG_OPENRule())
			return getTAG_OPENToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getTAG_OPEN2Rule())
			return getTAG_OPEN2Token(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * terminal ID  		: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	 */
	protected String getIDToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "";
	}
	
	/**
	 * TAG_CLOSE: '>';
	 */
	protected String getTAG_CLOSEToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return ">";
	}
	
	/**
	 * TAG_CLOSE2: '/>';
	 */
	protected String getTAG_CLOSE2Token(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "/>";
	}
	
	/**
	 * TAG_OPEN: '<'Namespace?;
	 */
	protected String getTAG_OPENToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "<";
	}
	
	/**
	 * TAG_OPEN2: '</'Namespace?;
	 */
	protected String getTAG_OPEN2Token(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "</";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if(match_Math_ConstantType_TAG_CLOSE2ParserRuleCall_7_0_or___TAG_CLOSEParserRuleCall_7_1_0_TAG_OPEN2ParserRuleCall_7_1_1_ConstantKeyword_7_1_2_TAG_CLOSEParserRuleCall_7_1_3__.equals(syntax))
				emit_Math_ConstantType_TAG_CLOSE2ParserRuleCall_7_0_or___TAG_CLOSEParserRuleCall_7_1_0_TAG_OPEN2ParserRuleCall_7_1_1_ConstantKeyword_7_1_2_TAG_CLOSEParserRuleCall_7_1_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Math_Otherwise_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_OtherwiseKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__.equals(syntax))
				emit_Math_Otherwise_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_OtherwiseKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Math_PiecewiseType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_PiecewiseKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__.equals(syntax))
				emit_Math_PiecewiseType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_PiecewiseKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Math_ScalarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_ScalarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__.equals(syntax))
				emit_Math_ScalarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_ScalarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Math_StringType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_StringKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__.equals(syntax))
				emit_Math_StringType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_StringKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Math_VarType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_VarKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__.equals(syntax))
				emit_Math_VarType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_VarKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Mml_FuncParameterDefinitionType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_2_FunctionArgumentKeyword_6_1_3_TAG_CLOSEParserRuleCall_6_1_4__.equals(syntax))
				emit_Mml_FuncParameterDefinitionType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_2_FunctionArgumentKeyword_6_1_3_TAG_CLOSEParserRuleCall_6_1_4__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_XS_xmlns_XmlnsKeyword_0_0_or_XsiKeyword_0_1.equals(syntax))
				emit_XS_xmlns_XmlnsKeyword_0_0_or_XsiKeyword_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_XS_xmlns___ColonKeyword_1_0___IDTerminalRuleCall_1_1_0_or_XsiKeyword_1_1_1____q.equals(syntax))
				emit_XS_xmlns___ColonKeyword_1_0___IDTerminalRuleCall_1_1_0_or_XsiKeyword_1_1_1____q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_ct_CellType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_CellKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__.equals(syntax))
				emit_ct_CellType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_CellKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_ct_ColumnType_TAG_CLOSE2ParserRuleCall_9_0_or___TAG_CLOSEParserRuleCall_9_1_0_TAG_OPEN2ParserRuleCall_9_1_1_ColumnKeyword_9_1_2_TAG_CLOSEParserRuleCall_9_1_3__.equals(syntax))
				emit_ct_ColumnType_TAG_CLOSE2ParserRuleCall_9_0_or___TAG_CLOSEParserRuleCall_9_1_0_TAG_OPEN2ParserRuleCall_9_1_1_ColumnKeyword_9_1_2_TAG_CLOSEParserRuleCall_9_1_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_ct_DefinitionRhsType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_DefinitionKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__.equals(syntax))
				emit_ct_DefinitionRhsType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_DefinitionKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_ct_DefinitionType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_DefinitionKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__.equals(syntax))
				emit_ct_DefinitionType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_DefinitionKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_ct_ExternalSourceType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_ExternalSourceKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__.equals(syntax))
				emit_ct_ExternalSourceType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_ExternalSourceKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_ct_InternalSourceType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_InternalSourceKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__.equals(syntax))
				emit_ct_InternalSourceType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_InternalSourceKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_ct_ReplicatesType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_ReplicatesKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__.equals(syntax))
				emit_ct_ReplicatesType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_ReplicatesKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_ct_RestrictionType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_RestrictionKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__.equals(syntax))
				emit_ct_RestrictionType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_RestrictionKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_ct_RowType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_RowKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__.equals(syntax))
				emit_ct_RowType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_RowKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_ct_SequenceType_TAG_CLOSE2ParserRuleCall_11_0_or___TAG_CLOSEParserRuleCall_11_1_0_TAG_OPEN2ParserRuleCall_11_1_1_SequenceKeyword_11_1_2_TAG_CLOSEParserRuleCall_11_1_3__.equals(syntax))
				emit_ct_SequenceType_TAG_CLOSE2ParserRuleCall_11_0_or___TAG_CLOSEParserRuleCall_11_1_0_TAG_OPEN2ParserRuleCall_11_1_1_SequenceKeyword_11_1_2_TAG_CLOSEParserRuleCall_11_1_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_ct_VariableDefinitionType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_3_VariableKeyword_4_1_4_TAG_CLOSEParserRuleCall_4_1_5__.equals(syntax))
				emit_ct_VariableDefinitionType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_3_VariableKeyword_4_1_4_TAG_CLOSEParserRuleCall_4_1_5__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_ct_VectorType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_3_VectorKeyword_4_1_4_TAG_CLOSEParserRuleCall_4_1_5__.equals(syntax))
				emit_ct_VectorType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_3_VectorKeyword_4_1_4_TAG_CLOSEParserRuleCall_4_1_5__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_design_DoseAmountType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_DoseAmountKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__.equals(syntax))
				emit_design_DoseAmountType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_DoseAmountKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_design_DoseVarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_DoseVarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__.equals(syntax))
				emit_design_DoseVarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_DoseVarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_design_DosingPeriodType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_DosingPeriodKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__.equals(syntax))
				emit_design_DosingPeriodType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_DosingPeriodKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_design_DosingRegimenType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_3_DosingRegimenKeyword_4_1_4_TAG_CLOSEParserRuleCall_4_1_5__.equals(syntax))
				emit_design_DosingRegimenType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_3_DosingRegimenKeyword_4_1_4_TAG_CLOSEParserRuleCall_4_1_5__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_design_TargetVarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_TargetVarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__.equals(syntax))
				emit_design_TargetVarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_TargetVarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_design_TreatmentEpochRefType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_TreatmentEpochRefKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__.equals(syntax))
				emit_design_TreatmentEpochRefType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_TreatmentEpochRefKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_design_TreatmentRefType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_TreatmentRefKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__.equals(syntax))
				emit_design_TreatmentRefType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_TreatmentRefKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_design_WashoutType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_WashoutKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__.equals(syntax))
				emit_design_WashoutType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_WashoutKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_mSteps_VariableEstimateType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_4_VariableKeyword_4_1_5_TAG_CLOSEParserRuleCall_4_1_6__.equals(syntax))
				emit_mSteps_VariableEstimateType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_4_VariableKeyword_4_1_5_TAG_CLOSEParserRuleCall_4_1_6__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_mdef_CategoricalType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_CategoricalKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__.equals(syntax))
				emit_mdef_CategoricalType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_CategoricalKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_mdef_CategoryType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_2_CategoryKeyword_5_1_3_TAG_CLOSEParserRuleCall_5_1_4__.equals(syntax))
				emit_mdef_CategoryType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_2_CategoryKeyword_5_1_3_TAG_CLOSEParserRuleCall_5_1_4__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_mdef_CovariateVariabilityType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_3_CovariateKeyword_6_1_4_TAG_CLOSEParserRuleCall_6_1_5__.equals(syntax))
				emit_mdef_CovariateVariabilityType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_3_CovariateKeyword_6_1_4_TAG_CLOSEParserRuleCall_6_1_5__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_mdef_ModelDefinitionType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_6_ModelDefinitionKeyword_4_1_7_TAG_CLOSEParserRuleCall_4_1_8__.equals(syntax))
				emit_mdef_ModelDefinitionType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_6_ModelDefinitionKeyword_4_1_7_TAG_CLOSEParserRuleCall_4_1_8__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_mdef_ObservationModelType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_3_ObservationModelKeyword_5_1_4_TAG_CLOSEParserRuleCall_5_1_5__.equals(syntax))
				emit_mdef_ObservationModelType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_3_ObservationModelKeyword_5_1_4_TAG_CLOSEParserRuleCall_5_1_5__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_mdef_Param1VarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_Param1VarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__.equals(syntax))
				emit_mdef_Param1VarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_Param1VarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_mdef_Param2VarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_Param2VarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__.equals(syntax))
				emit_mdef_Param2VarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_Param2VarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_mdef_ParameterType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_6_ParameterKeyword_6_1_7_TAG_CLOSEParserRuleCall_6_1_8__.equals(syntax))
				emit_mdef_ParameterType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_6_ParameterKeyword_6_1_7_TAG_CLOSEParserRuleCall_6_1_8__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_mdef_StructuralModelType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_6_StructuralModelKeyword_4_1_7_TAG_CLOSEParserRuleCall_4_1_8__.equals(syntax))
				emit_mdef_StructuralModelType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_6_StructuralModelKeyword_4_1_7_TAG_CLOSEParserRuleCall_4_1_8__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_mdef_VariabilityLevelDefnType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_VariabilityLevelKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__.equals(syntax))
				emit_mdef_VariabilityLevelDefnType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_VariabilityLevelKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_msteps_ColumnMappingType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_3_MappingKeyword_6_1_4_TAG_CLOSEParserRuleCall_6_1_5__.equals(syntax))
				emit_msteps_ColumnMappingType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_3_MappingKeyword_6_1_4_TAG_CLOSEParserRuleCall_6_1_5__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_msteps_DependantStepType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_DependantStepKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__.equals(syntax))
				emit_msteps_DependantStepType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_DependantStepKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_msteps_EstimationOperationType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_EstimationOperationKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__.equals(syntax))
				emit_msteps_EstimationOperationType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_EstimationOperationKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_msteps_InitialValueType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_2_InitialValueKeyword_5_1_3_TAG_CLOSEParserRuleCall_5_1_4__.equals(syntax))
				emit_msteps_InitialValueType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_2_InitialValueKeyword_5_1_3_TAG_CLOSEParserRuleCall_5_1_4__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_msteps_ParametersToEstimateType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_ParametersToEstimateKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__.equals(syntax))
				emit_msteps_ParametersToEstimateType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_ParametersToEstimateKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_msteps_SimulationStep_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_6_SimulationStepKeyword_4_1_7_TAG_CLOSEParserRuleCall_4_1_8__.equals(syntax))
				emit_msteps_SimulationStep_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_6_SimulationStepKeyword_4_1_7_TAG_CLOSEParserRuleCall_4_1_8__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_msteps_StepType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_2_StepKeyword_6_1_3_TAG_CLOSEParserRuleCall_6_1_4__.equals(syntax))
				emit_msteps_StepType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_2_StepKeyword_6_1_3_TAG_CLOSEParserRuleCall_6_1_4__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_msteps_TargetVarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_TargetVarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__.equals(syntax))
				emit_msteps_TargetVarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_TargetVarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_msteps_UseVariabilityLevel_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_UseVariabilityLevelKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__.equals(syntax))
				emit_msteps_UseVariabilityLevel_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_UseVariabilityLevelKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_msteps_UseVariabilityNode_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_UseVariabilityNodeKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__.equals(syntax))
				emit_msteps_UseVariabilityNode_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_UseVariabilityNodeKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_uncert_ParameterDefinitionType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_FunctionParameterKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__.equals(syntax))
				emit_uncert_ParameterDefinitionType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_FunctionParameterKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_uncert_StdDev_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_StdDevKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__.equals(syntax))
				emit_uncert_StdDev_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_StdDevKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_uncert_Uniform_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_UniformKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__.equals(syntax))
				emit_uncert_Uniform_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_UniformKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Syntax:
	 *     (TAG_CLOSE TAG_OPEN2 'Constant' TAG_CLOSE) | TAG_CLOSE2
	 */
	protected void emit_Math_ConstantType_TAG_CLOSE2ParserRuleCall_7_0_or___TAG_CLOSEParserRuleCall_7_1_0_TAG_OPEN2ParserRuleCall_7_1_1_ConstantKeyword_7_1_2_TAG_CLOSEParserRuleCall_7_1_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     (TAG_CLOSE TAG_OPEN2 'Otherwise' TAG_CLOSE) | TAG_CLOSE2
	 */
	protected void emit_Math_Otherwise_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_OtherwiseKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     (TAG_CLOSE TAG_OPEN2 'Piecewise' TAG_CLOSE) | TAG_CLOSE2
	 */
	protected void emit_Math_PiecewiseType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_PiecewiseKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     (TAG_CLOSE TAG_OPEN2 'Scalar' TAG_CLOSE) | TAG_CLOSE2
	 */
	protected void emit_Math_ScalarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_ScalarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'String' TAG_CLOSE)
	 */
	protected void emit_Math_StringType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_StringKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'Var' TAG_CLOSE)
	 */
	protected void emit_Math_VarType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_VarKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'FunctionArgument' TAG_CLOSE)
	 */
	protected void emit_Mml_FuncParameterDefinitionType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_2_FunctionArgumentKeyword_6_1_3_TAG_CLOSEParserRuleCall_6_1_4__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'xsi' | 'xmlns'
	 */
	protected void emit_XS_xmlns_XmlnsKeyword_0_0_or_XsiKeyword_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     (':' ('xsi' | ID))?
	 */
	protected void emit_XS_xmlns___ColonKeyword_1_0___IDTerminalRuleCall_1_1_0_or_XsiKeyword_1_1_1____q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'Cell' TAG_CLOSE)
	 */
	protected void emit_ct_CellType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_CellKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     (TAG_CLOSE TAG_OPEN2 'Column' TAG_CLOSE) | TAG_CLOSE2
	 */
	protected void emit_ct_ColumnType_TAG_CLOSE2ParserRuleCall_9_0_or___TAG_CLOSEParserRuleCall_9_1_0_TAG_OPEN2ParserRuleCall_9_1_1_ColumnKeyword_9_1_2_TAG_CLOSEParserRuleCall_9_1_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'Definition' TAG_CLOSE)
	 */
	protected void emit_ct_DefinitionRhsType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_DefinitionKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     (TAG_CLOSE TAG_OPEN2 'Definition' TAG_CLOSE) | TAG_CLOSE2
	 */
	protected void emit_ct_DefinitionType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_DefinitionKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'ExternalSource' TAG_CLOSE)
	 */
	protected void emit_ct_ExternalSourceType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_ExternalSourceKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'InternalSource' TAG_CLOSE)
	 */
	protected void emit_ct_InternalSourceType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_InternalSourceKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'Replicates' TAG_CLOSE)
	 */
	protected void emit_ct_ReplicatesType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_ReplicatesKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     (TAG_CLOSE TAG_OPEN2 'Restriction' TAG_CLOSE) | TAG_CLOSE2
	 */
	protected void emit_ct_RestrictionType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_RestrictionKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'Row' TAG_CLOSE)
	 */
	protected void emit_ct_RowType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_RowKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     (TAG_CLOSE TAG_OPEN2 'Sequence' TAG_CLOSE) | TAG_CLOSE2
	 */
	protected void emit_ct_SequenceType_TAG_CLOSE2ParserRuleCall_11_0_or___TAG_CLOSEParserRuleCall_11_1_0_TAG_OPEN2ParserRuleCall_11_1_1_SequenceKeyword_11_1_2_TAG_CLOSEParserRuleCall_11_1_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'Variable' TAG_CLOSE)
	 */
	protected void emit_ct_VariableDefinitionType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_3_VariableKeyword_4_1_4_TAG_CLOSEParserRuleCall_4_1_5__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     (TAG_CLOSE TAG_OPEN2 'Vector' TAG_CLOSE) | TAG_CLOSE2
	 */
	protected void emit_ct_VectorType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_3_VectorKeyword_4_1_4_TAG_CLOSEParserRuleCall_4_1_5__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     (TAG_CLOSE TAG_OPEN2 'DoseAmount' TAG_CLOSE) | TAG_CLOSE2
	 */
	protected void emit_design_DoseAmountType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_DoseAmountKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'DoseVar' TAG_CLOSE)
	 */
	protected void emit_design_DoseVarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_DoseVarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     (TAG_CLOSE TAG_OPEN2 'DosingPeriod' TAG_CLOSE) | TAG_CLOSE2
	 */
	protected void emit_design_DosingPeriodType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_DosingPeriodKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'DosingRegimen' TAG_CLOSE)
	 */
	protected void emit_design_DosingRegimenType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_3_DosingRegimenKeyword_4_1_4_TAG_CLOSEParserRuleCall_4_1_5__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     (TAG_CLOSE TAG_OPEN2 'TargetVar' TAG_CLOSE) | TAG_CLOSE2
	 */
	protected void emit_design_TargetVarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_TargetVarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'TreatmentEpochRef' TAG_CLOSE)
	 */
	protected void emit_design_TreatmentEpochRefType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_TreatmentEpochRefKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'TreatmentRef' TAG_CLOSE)
	 */
	protected void emit_design_TreatmentRefType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_TreatmentRefKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'Washout' TAG_CLOSE)
	 */
	protected void emit_design_WashoutType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_WashoutKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'Variable' TAG_CLOSE)
	 */
	protected void emit_mSteps_VariableEstimateType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_4_VariableKeyword_4_1_5_TAG_CLOSEParserRuleCall_4_1_6__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'Categorical' TAG_CLOSE)
	 */
	protected void emit_mdef_CategoricalType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_CategoricalKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'Category' TAG_CLOSE)
	 */
	protected void emit_mdef_CategoryType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_2_CategoryKeyword_5_1_3_TAG_CLOSEParserRuleCall_5_1_4__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     (TAG_CLOSE TAG_OPEN2 'Covariate' TAG_CLOSE) | TAG_CLOSE2
	 */
	protected void emit_mdef_CovariateVariabilityType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_3_CovariateKeyword_6_1_4_TAG_CLOSEParserRuleCall_6_1_5__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     (TAG_CLOSE TAG_OPEN2 'ModelDefinition' TAG_CLOSE) | TAG_CLOSE2
	 */
	protected void emit_mdef_ModelDefinitionType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_6_ModelDefinitionKeyword_4_1_7_TAG_CLOSEParserRuleCall_4_1_8__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     (TAG_CLOSE TAG_OPEN2 'ObservationModel' TAG_CLOSE) | TAG_CLOSE2
	 */
	protected void emit_mdef_ObservationModelType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_3_ObservationModelKeyword_5_1_4_TAG_CLOSEParserRuleCall_5_1_5__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'Param1Var' TAG_CLOSE)
	 */
	protected void emit_mdef_Param1VarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_Param1VarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'Param2Var' TAG_CLOSE)
	 */
	protected void emit_mdef_Param2VarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_Param2VarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     (TAG_CLOSE TAG_OPEN2 'Parameter' TAG_CLOSE) | TAG_CLOSE2
	 */
	protected void emit_mdef_ParameterType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_6_ParameterKeyword_6_1_7_TAG_CLOSEParserRuleCall_6_1_8__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'StructuralModel' TAG_CLOSE)
	 */
	protected void emit_mdef_StructuralModelType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_6_StructuralModelKeyword_4_1_7_TAG_CLOSEParserRuleCall_4_1_8__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'VariabilityLevel' TAG_CLOSE)
	 */
	protected void emit_mdef_VariabilityLevelDefnType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_VariabilityLevelKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     (TAG_CLOSE TAG_OPEN2 'Mapping' TAG_CLOSE) | TAG_CLOSE2
	 */
	protected void emit_msteps_ColumnMappingType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_3_MappingKeyword_6_1_4_TAG_CLOSEParserRuleCall_6_1_5__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'DependantStep' TAG_CLOSE)
	 */
	protected void emit_msteps_DependantStepType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_DependantStepKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     (TAG_CLOSE TAG_OPEN2 'EstimationOperation' TAG_CLOSE) | TAG_CLOSE2
	 */
	protected void emit_msteps_EstimationOperationType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_EstimationOperationKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'InitialValue' TAG_CLOSE)
	 */
	protected void emit_msteps_InitialValueType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_2_InitialValueKeyword_5_1_3_TAG_CLOSEParserRuleCall_5_1_4__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'ParametersToEstimate' TAG_CLOSE)
	 */
	protected void emit_msteps_ParametersToEstimateType_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_ParametersToEstimateKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     (TAG_CLOSE TAG_OPEN2 'SimulationStep' TAG_CLOSE) | TAG_CLOSE2
	 */
	protected void emit_msteps_SimulationStep_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_6_SimulationStepKeyword_4_1_7_TAG_CLOSEParserRuleCall_4_1_8__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'Step' TAG_CLOSE)
	 */
	protected void emit_msteps_StepType_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_2_StepKeyword_6_1_3_TAG_CLOSEParserRuleCall_6_1_4__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'TargetVar' TAG_CLOSE)
	 */
	protected void emit_msteps_TargetVarType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_TargetVarKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'UseVariabilityLevel' TAG_CLOSE)
	 */
	protected void emit_msteps_UseVariabilityLevel_TAG_CLOSE2ParserRuleCall_6_0_or___TAG_CLOSEParserRuleCall_6_1_0_TAG_OPEN2ParserRuleCall_6_1_1_UseVariabilityLevelKeyword_6_1_2_TAG_CLOSEParserRuleCall_6_1_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     (TAG_CLOSE TAG_OPEN2 'UseVariabilityNode' TAG_CLOSE) | TAG_CLOSE2
	 */
	protected void emit_msteps_UseVariabilityNode_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_UseVariabilityNodeKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'FunctionParameter' TAG_CLOSE)
	 */
	protected void emit_uncert_ParameterDefinitionType_TAG_CLOSE2ParserRuleCall_5_0_or___TAG_CLOSEParserRuleCall_5_1_0_TAG_OPEN2ParserRuleCall_5_1_1_FunctionParameterKeyword_5_1_2_TAG_CLOSEParserRuleCall_5_1_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'StdDev' TAG_CLOSE)
	 */
	protected void emit_uncert_StdDev_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_2_StdDevKeyword_4_1_3_TAG_CLOSEParserRuleCall_4_1_4__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     TAG_CLOSE2 | (TAG_CLOSE TAG_OPEN2 'Uniform' TAG_CLOSE)
	 */
	protected void emit_uncert_Uniform_TAG_CLOSE2ParserRuleCall_4_0_or___TAG_CLOSEParserRuleCall_4_1_0_TAG_OPEN2ParserRuleCall_4_1_1_UniformKeyword_4_1_2_TAG_CLOSEParserRuleCall_4_1_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
