/*
 * generated by Xtext
 */
package eu.ddmore.pml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PharmMLUiModule extends eu.ddmore.pml.ui.AbstractPharmMLUiModule {
	public PharmMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
