<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pharmML" nsURI="http://www.ddmore.eu/pml/PharmML" nsPrefix="pharmML">
  <eClassifiers xsi:type="ecore:EClass" name="Mml_PharmML">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//ct_name"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="independentVar" eType="#//ct_independentVar"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="writtenVersion" eType="#//ct_writtenVersion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SymbolDefinition" upperBound="-1"
        eType="#//Mml_SymbolDefinitionType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" upperBound="-1" eType="#//Mml_PharmaMLContent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Design" eType="#//design_TrialDesignType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ModelingSteps" eType="#//msteps_ModelingSteps"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mml_PharmaMLContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="StructuralModel" eType="#//mdef_StructuralModelType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ModelDefinition" eType="#//mdef_ModelDefinitionType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mml_SymbolDefinitionType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//ct_name"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbId" eType="#//ct_symbId"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbolType" eType="#//ct_symbolType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Description" eType="#//ct_AnnotationType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FunctionDefinition" eType="#//Mml_FunctionDefinitionType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mml_FunctionDefinitionType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FunctionArguments" upperBound="-1"
        eType="#//Mml_FuncParameterDefinitionType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Definition" eType="#//ct_DefinitionRhsType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mml_FuncParameterDefinitionType"/>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_ModelDefinitionType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VariabilityLevel" upperBound="-1"
        eType="#//mdef_VariabilityLevelDefnType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CovariateModel" eType="#//mdef_CovariateModelType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ParameterModel" eType="#//mdef_ParameterModelType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="StructuraModel" upperBound="-1"
        eType="#//mdef_StructuralModelType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ObservationModel" eType="#//mdef_ObservationModelType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_ParameterTypeName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="log" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="none" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_StructuralModelType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="#//ct_id" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Description" eType="#//ct_AnnotationType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Parameter" upperBound="-1"
        eType="#//mdef_ParameterType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Variable" upperBound="-1"
        eType="#//ct_VariableDefinitionType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Import" upperBound="-1"
        eType="#//mdef_ImportType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="InitiaCondition" upperBound="-1"
        eType="#//mdef_InitialConditionType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_ObservationModelType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="#//ct_id" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//ct_name"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Parameter" upperBound="-1"
        eType="#//mdef_ParameterType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Continuous" upperBound="-1"
        eType="#//mdef_ContinuousObsModelType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_ContinuousObsModelType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbId" eType="#//ct_symbId"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Var" eType="#//Math_VarType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ErrorModel" eType="#//mdef_ErrorModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RandomEffect" upperBound="-1"
        eType="#//mdef_RandomEffectType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_ErrorModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Var" eType="#//Math_VarType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FunctionArgument" upperBound="-1"
        eType="#//Math_FunctionArgumentType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_RandomEffectType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Distribution" eType="#//uncert_DistributionType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_ParameterModelType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="#//ct_id" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//ct_name"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Parameter" upperBound="-1"
        eType="#//mdef_ParameterType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Correlation" upperBound="-1"
        eType="#//mdef_CorrelationType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_CorrelationType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="levelId" eType="#//ct_levelId"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ParamVar1" eType="#//mdef_Param1VarType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ParamVar2" eType="#//mdef_Param2VarType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CorrelationCoefficient"
        eType="#//mdef_CorrelationCoefficientType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Covariance" eType="#//mdefCovarianceType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_Param1VarType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//Math_block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbId" eType="#//Math_symbId"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_Param2VarType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//Math_block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbId" eType="#//Math_symbId"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdefCovarianceType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//ct_ScalarRhs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_CorrelationCoefficientType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//ct_ScalarRhs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_CovariateModelType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="#//ct_id" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//ct_name"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Parameter" upperBound="-1"
        eType="#//mdef_ParameterType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Covariate" upperBound="-1"
        eType="#//mdef_CovariateVariabilityType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_ParameterType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//ct_name"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbId" eType="#//Math_symbId"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformation" eType="#//mdef_transformation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Var" eType="#//Math_VarType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Scalar" eType="#//Math_ScalarType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Equation" eType="#//Math_EquationType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RandomEffect" upperBound="-1"
        eType="#//mdef_ParameterRandomEffectType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Covariate" upperBound="-1"
        eType="#//mdef_CovariateType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_CovariateVariabilityType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//ct_name"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbId" eType="#//ct_symbId"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformation" eType="#//mdef_transformation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Continuous" eType="#//mdef_ContinuousCovariateType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Categorical" eType="#//mdef_CategoricalType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_transformation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformation" eType="#//mdef_ParameterTypeName"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_CategoricalType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Category" upperBound="-1"
        eType="#//mdef_CategoryType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_ContinuousCovariateType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Distribution" eType="#//uncert_DistributionType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Transformation" eType="#//mdef_TransformationType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_TransformationType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//ct_Rhs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_VariabilityLevelDefnType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="#//ct_id" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//ct_name"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_ImportType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceType" eType="#//mdef_ImportResourceTypeType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Link" upperBound="-1" eType="#//mdef_ImportLinkType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_ImportLinkType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbolPtr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Var" eType="#//Math_VarType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_ImportResourceTypeType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sbml" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pharmml" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_CovariateType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Var" eType="#//Math_VarType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FixedEffect" upperBound="-1"
        eType="#//mdef_FixedEffectType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_FixedEffectType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Var" eType="#//Math_VarType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Category" eType="#//mdef_CategoryType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_CategoryType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="catId" eType="#//ct_catId"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//ct_name"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Probability" eType="#//mdef_ProbabilityType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_ProbabilityType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//ct_Rhs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_ParameterRandomEffectType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="levelId" eType="#//ct_levelId"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//ct_name"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbId" eType="#//ct_symbId"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Distribution" eType="#//uncert_DistributionType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdef_InitialConditionType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//Math_block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbID" eType="#//Math_symbId"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//ct_Rhs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="msteps_ModelingSteps">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Variable" upperBound="-1"
        eType="#//ct_VariableDefinitionType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" upperBound="-1" eType="#//msteps_ModelingStepsContent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="StepDependencies" eType="#//msteps_StepDependenciesType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="msteps_ModelingStepsContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EstimationStep" eType="#//msteps_EstimationStep"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SimulationStep" eType="#//msteps_SimulationStep"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="msteps_StepDependenciesType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Description" eType="#//ct_AnnotationType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Step" upperBound="-1" eType="#//msteps_StepType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="msteps_StepType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idRef" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DependantStep" upperBound="-1"
        eType="#//msteps_DependantStepType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="msteps_DependantStepType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idRef" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="msteps_EstimationStep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="#//ct_id" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Description" eType="#//ct_AnnotationType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="InitialValue" upperBound="-1"
        eType="#//msteps_InitialValueType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ObjectiveDataSet" eType="#//msteps_ObjectiveDataSetType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ParametersToEstimate" eType="#//msteps_ParametersToEstimateType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EstimationOperation" upperBound="-1"
        eType="#//msteps_EstimationOperationType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="msteps_ParametersToEstimateType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Variable" upperBound="-1"
        eType="#//mSteps_VariableEstimateType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mSteps_VariableEstimateType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//Math_block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fixed" eType="#//mSteps_fixed"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbID" eType="#//Math_symbId"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="InitialEstimate" eType="#//mSteps_InitialEstimateType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LowerBound" eType="#//mSteps_LowerBoundType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="UpperBound" eType="#//mSteps_UpperBoundType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mSteps_fixed">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fixed" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mSteps_UpperBoundType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//ct_ScalarRhs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mSteps_LowerBoundType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//ct_ScalarRhs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mSteps_InitialEstimateType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//ct_ScalarRhs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="msteps_ObjectiveDataSetType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSetRef" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Mapping" upperBound="-1"
        eType="#//msteps_ColumnMappingType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="msteps_ColumnMappingType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" upperBound="-1" eType="#//msteps_ColumnMappingTypeContent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Restriction" eType="#//ct_RestrictionType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="msteps_ColumnMappingTypeContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Var" eType="#//Math_VarType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="UseVariabilityLevel" eType="#//msteps_UseVariabilityLevel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="UseVariabilityNode" eType="#//msteps_UseVariabilityNode"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DoseVar" eType="#//design_DoseVarType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TargetVar" eType="#//msteps_TargetVarType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Assign" eType="#//msteps_AssignType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Output" eType="#//msteps_OutputType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="msteps_OutputType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Vars" eType="#//Math_VarType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="msteps_AssignType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//Math_block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbId" eType="#//Math_symbId"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//ct_Rhs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="msteps_TargetVarType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//Math_block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbId" eType="#//Math_symbId"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="msteps_UseVariabilityLevel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="levelId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="msteps_UseVariabilityNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//Math_block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbId" eType="#//Math_symbId"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="msteps_SimulationStep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="#//ct_id" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Description" eType="#//ct_AnnotationType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Replicates" eType="#//ct_ReplicatesType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="InitialValue" upperBound="-1"
        eType="#//msteps_InitialValueType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SimDataSet" eType="#//msteps_SimDataSetType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Observations" upperBound="-1"
        eType="#//msteps_ObservationsType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="msteps_SimDataSetType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSetRef" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Mapping" upperBound="-1"
        eType="#//msteps_ColumnMappingType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="msteps_ObservationsType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Timepoints" eType="#//msteps_TimepointsType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Output" upperBound="-1"
        eType="#//msteps_OutputType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="WriteTo" upperBound="-1"
        eType="#//msteps_WriteToType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="msteps_WriteToType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Var" eType="#//Math_VarType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Mapping" upperBound="-1"
        eType="#//msteps_ColumnMappingType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="msteps_TimepointsType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//ct_Rhs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="msteps_InitialValueType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//ct_block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbId" eType="#//ct_symbId"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//ct_Rhs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="msteps_EstimationOperationType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="opType" eType="#//Math_EstimationOperationType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_TrialDesignType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Treatment" upperBound="-1"
        eType="#//design_TreatmentType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TreatmentEpoch" upperBound="-1"
        eType="#//design_TreatmentEpohType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Group" upperBound="-1"
        eType="#//design_GroupType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_GroupType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="#//ct_id" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//ct_name"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" upperBound="-1" eType="#//design_GroupTypeContent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Individuals" eType="#//design_IdividualsType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_GroupTypeContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="TreatmentEpochRef" eType="#//design_TreatmentEpochRefType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Washout" eType="#//design_WashoutType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_IdividualsType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="levelId" eType="#//ct_levelId"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//ct_name"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbId" eType="#//ct_symbId"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//ct_Rhs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_WashoutType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_TreatmentEpohType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="#//ct_id" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//ct_name"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TreatmentRef" upperBound="-1"
        eType="#//design_TreatmentRefType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Start" eType="#//design_StartType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="End" eType="#//design_EndType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Occasion" upperBound="-1"
        eType="#//design_OccasionType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_OccasionType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="levelId" eType="#//ct_levelId"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//ct_name"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbId" eType="#//ct_symbId"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Begin" eType="#//design_BeginType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="End" eType="#//design_EndType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_BeginType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//ct_ScalarRhs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_EndType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//ct_ScalarRhs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_StartType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//ct_ScalarRhs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_TreatmentRefType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idRef" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_TreatmentEpochRefType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idRef" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_TreatmentType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="#//Math_id"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//ct_name"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DosingRegimen" upperBound="-1"
        eType="#//design_DosingRegimenType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_DosingRegimenType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Bolus" eType="#//design_BolusType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Infusion" eType="#//design_InfusionType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_InfusionType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DoseAmount" eType="#//design_DoseAmountType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SteadyState" eType="#//design_SteadyStateType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DosingTimes" eType="#//design_DosingTimesType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Duration" eType="#//design_DurationType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_DurationType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//design_DosingVariableType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_BolusType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DoseAmount" eType="#//design_DoseAmountType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SteadyState" eType="#//design_SteadyStateType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DosingTimes" eType="#//design_DosingTimesType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_DosingTimesType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" upperBound="-1" eType="#//design_DosingTimesTypeContent"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_DosingTimesTypeContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Sequence" eType="#//ct_SequenceType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Scalar" eType="#//Math_ScalarType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_SteadyStateType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DosingStart" eType="#//design_DosingStartType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DosingPeriod" eType="#//design_DosingPeriodType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_DosingStartType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//design_DosingVariableType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_DosingPeriodType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//design_DosingVariableType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_DoseAmountType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//design_DosingVariableType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_DosingVariableType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//design_DosingVariableTypeContent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Amount" eType="#//design_AmountType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_DosingVariableTypeContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="DoseVar" eType="#//design_DoseVarType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TargetVar" eType="#//design_TargetVarType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_AmountType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//ct_Rhs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_TargetVarType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//Math_block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbId" eType="#//Math_symbId"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_DoseVarType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//Math_block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbId" eType="#//Math_symbId"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="uncert_DistributionType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="writtenVersion" eType="#//ct_writtenVersion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//uncert_DistributionTypeContent"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="uncert_DistributionTypeContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Normal" eType="#//uncert_Normal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PDF" eType="#//uncert_PDF"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Poison" eType="#//uncert_Poison"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Student" eType="#//uncert_Student_t"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Uniform" eType="#//uncert_Uniform"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="uncert_Normal">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Mean" eType="#//uncert_Mean"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="StdDev" eType="#//uncert_StdDev"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Variance" eType="#//uncert_Variance"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CoefficientOfVariance"
        eType="#//uncert_CoefficientOfVariance" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="uncert_CoefficientOfVariance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//uncert_DistributionParamType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="uncert_StdDev">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" upperBound="-1" eType="#//uncert_DistributionParamType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="uncert_DistributionParamType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Equation" eType="#//Math_EquationType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Scalar" eType="#//Math_ScalarType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Var" eType="#//Math_VarType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="uncert_MeanParamType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//uncert_DistributionParamType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="uncert_Mean">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//uncert_MeanParamType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="uncert_Variance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//uncert_DistributionParamType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="uncert_PDF">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FunctionParameter" upperBound="-1"
        eType="#//uncert_ParameterDefinitionType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Equation" eType="#//Math_EquationType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="uncert_ParameterDefinitionType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="#//Math_id"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//ct_name"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="uncert_Poison">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Rate" eType="#//uncert_Rate"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="uncert_Rate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//uncert_DistributionParamType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="uncert_Student_t">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Location" eType="#//uncert_Location"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Scale" eType="#//uncert_Scale"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DegreesOfFreedom" eType="#//uncertDegreesOfFreedom"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="uncertDegreesOfFreedom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//uncert_DistributionParamType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="uncert_Scale">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//uncert_DistributionParamType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="uncert_Location">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//uncert_DistributionParamType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="uncert_Uniform">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_EquationType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="writtenVersion" eType="#//ct_writtenVersion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//Math_EquationTypeContent"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_EquationTypeContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Scalar" eType="#//Math_ScalarType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Var" eType="#//Math_VarType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Binop" eType="#//Math_BinopType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Uniop" eType="#//Math_UniopType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Piecewise" eType="#//Math_PiecewiseType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_ScalarType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ct_Decimal_Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_VarType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//Math_block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbId" eType="#//Math_symbId"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_BinopType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="op" eType="#//Math_BinopName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LeftExpr" eType="#//Math_ExprType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RightExpr" eType="#//Math_ExprType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_UniopType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="op" eType="#//Math_UniopName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//Math_ExprType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_ExprType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Scalar" eType="#//Math_ScalarType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Var" eType="#//Math_VarType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Uniop" eType="#//Math_UniopType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Binop" eType="#//Math_BinopType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Constant" eType="#//Math_ConstantType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FunctionCall" eType="#//Math_FunctionCallType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_ConstantType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="op" eType="#//Math_ConstantName"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_FunctionCallType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Functionname" eType="#//Math_VarType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FunctionArguments" upperBound="-1"
        eType="#//Math_FunctionArgumentType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_FunctionArgumentType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbId" eType="#//Math_symbId"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//Math_FuncExprType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_FuncExprType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Equation" eType="#//Math_EquationType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Scalar" eType="#//Math_ScalarType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Constant" eType="#//Math_ConstantType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Var" eType="#//Math_VarType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_PiecewiseType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Piecewise" upperBound="-1"
        eType="#//Math_PieceType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_PieceType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Content" eType="#//Math_ExprType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Condition" eType="#//Math_ConditionType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_ConditionType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="writtenVersion" eType="#//ct_writtenVersion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//Math_LogicBaseType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_LogicBaseType" eSuperTypes="#//Math_LogicExprType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="LogicBinopType" eType="#//Math_LogicBinopType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LogicUniopType" eType="#//Math_LogicUniopType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="True" eType="#//Math_TRUE"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="False" eType="#//Math_FALSE"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Otherwise" eType="#//Math_Otherwise"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_Otherwise">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_LogicExprType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Scalar" eType="#//Math_ScalarType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Constant" eType="#//Math_ConstantType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Var" eType="#//Math_VarType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Uniop" eType="#//Math_UniopType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Binop" eType="#//Math_BinopType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FunctionCall" eType="#//Math_FunctionCallType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="String" eType="#//Math_StringType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_StringType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ct_String_Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_TRUE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="true" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_FALSE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_LogicBinopType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="op" eType="#//Math_LogicBinopName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LeftExpr" eType="#//Math_LogicExprType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RightExpr" eType="#//Math_LogicExprType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_LogicUniopType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="op" eType="#//Math_LogicUniopName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//Math_LogicExprType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_BinopName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="binopname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minus" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="times" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="divide" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="power" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="log" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="root" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_UniopName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ln" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minus" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factorial" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cos" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tan" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sec" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="csc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sinh" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="csch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arcsin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arccos" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arctan" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arcsec" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arccsc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arccot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arcsinh" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arccosh" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arctanh" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arcsech" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arccsch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arccoth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="floor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ceiling" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_LogicUniopName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDefined" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="not" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_LogicBinopName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="leq" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="geq" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eq" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="neq" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="and" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="or" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_ConstantName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="notanumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pi" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exponentiale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="infinity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_symbId">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_id">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="block" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Math_EstimationOperationType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="estPop" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="estFIM" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="estIndiv" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_ReplicatesType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbId" eType="#//ct_symbId"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//ct_Rhs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_AnnotationType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_Rhs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Equation" eType="#//Math_EquationType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Scalar" eType="#//Math_ScalarType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Constant" eType="#//Math_ConstantType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="String" eType="#//Math_StringType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Sequence" eType="#//ct_SequenceType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Vector" eType="#//ct_VectorType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FunctionCall" eType="#//Math_FunctionCallType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DataSet" eType="#//ct_DataSetType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Var" eType="#//Math_VarType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Distribution" eType="#//uncert_DistributionType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_DataSetType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Definition" eType="#//ct_DefinitionType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ExternalSource" upperBound="-1"
        eType="#//ct_ExternalSourceType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Row" upperBound="-1" eType="#//ct_RowType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="InternalSource" upperBound="-1"
        eType="#//ct_InternalSourceType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_DefinitionType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Definition" upperBound="-1"
        eType="#//ct_ColumnType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_DefinitionRhsType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Definition" eType="#//ct_Rhs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_ColumnType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnNum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnVar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_ExternalSourceType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="headerLine" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ignoreLineSymbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_RowType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Row" upperBound="-1" eType="#//ct_RowTypeContent"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_RowTypeContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Cell" eType="#//ct_CellType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Null" eType="#//ct_NullCellType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_NullCellType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="null" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_CellType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ct_Decimal_Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_InternalSourceType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//Math_block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbId" eType="#//Math_symbId"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_VectorType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Scalar" upperBound="-1"
        eType="#//Math_ScalarType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Sequence" upperBound="-1"
        eType="#//ct_SequenceType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_SequenceType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="begin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stepwise" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repetition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_VariableDefinitionType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="independentVar" eType="#//ct_independentVar"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbId" eType="#//ct_symbId"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbolType" eType="#//ct_symbolType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Description" eType="#//ct_AnnotationType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//ct_Rhs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_RestrictionType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="#//Math_ConditionType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_ScalarRhs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Equation" eType="#//Math_EquationType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Scalar" eType="#//Math_ScalarType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Var" eType="#//Math_VarType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="String" eType="#//Math_StringType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FunctionCall" eType="#//Math_FunctionCallType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_independentVar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="independentVar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_levelId">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="levelId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_name">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_symbId">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_id">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_symbolType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbolType" eType="#//ct_SymbolTypeType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="block" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_writtenVersion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="writtenVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_Decimal_Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_String_Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_catId">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="catId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ct_SymbolTypeType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scalar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derivative" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distrib" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSet" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XS_xmlns">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mml_FuncParameterDefinitionTyp" eSuperTypes="#//Mml_FuncParameterDefinitionType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" upperBound="-1"
        eType="#//XS_xmlns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sumbId" eType="#//ct_symbId"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbolType" eType="#//ct_symbolType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Decsription" eType="#//ct_AnnotationType"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
