CREATE DATABASE mif DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_bin;
CREATE USER 'mif'@'localhost' IDENTIFIED BY 'mif';
GRANT ALL ON mif.* TO 'mif'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;