/*******************************************************************************
 * Copyright (C) 2013 Mango Solutions Ltd - All rights reserved.
 ******************************************************************************/
package eu.ddmore.convertertoolbox.response;

import java.io.File;
import java.util.Map;

/**
 * Bean representing details generated by a conversion activity
 */
public interface ConversionDetail {

    File getFile();

    void setFile(File file);

    int getServerity();

    void setSeverity(int severity);

    Map<String, String> getInfo();

    void setInfo(Map<String, String> info);

    void addInfo(String key, String value);

    String getMessage();

    void setMessage(String message);
}
