/*
* generated by Xtext
*/
package eu.ddmore.pml.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import eu.ddmore.pml.services.PharmMLGrammarAccess;

public class PharmMLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PharmMLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected eu.ddmore.pml.parser.antlr.internal.InternalPharmMLParser createParser(XtextTokenStream stream) {
		return new eu.ddmore.pml.parser.antlr.internal.InternalPharmMLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Mml_PharmML";
	}
	
	public PharmMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PharmMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
