/*
* generated by Xtext
*/
package org.ddmore.pml.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class PharmaMLOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
