/*
 * generated by Xtext
 */
package org.ddmore.pml.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.ddmore.pml.ui.internal.PharmaMLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PharmaMLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PharmaMLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PharmaMLActivator.getInstance().getInjector(PharmaMLActivator.ORG_DDMORE_PML_PHARMAML);
	}
	
}
