/*
* generated by Xtext
*/
package org.ddmore.pml.ui.contentassist;

import org.ddmore.pml.ui.contentassist.AbstractPharmaMLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class PharmaMLProposalProvider extends AbstractPharmaMLProposalProvider {

}
